"""Veteran-track config (isolated from redraft/dynasty season windows)."""
from __future__ import annotations

from rookie_ppr.config import CSV_OUTPUT_DIR, LATEST_FANTASY_SEASON, MODELS_DIR, SKILL_POSITIONS

# Player-season history window (nflverse schedules/pbp-era core)
VET_SEASON_MIN = 1999
VET_SEASON_MAX = LATEST_FANTASY_SEASON  # last labeled fantasy season

# Row predicts target_season = season + 1
# Tune on 2021 targets; hold out 2022–2025 targets
VET_TUNING_TARGET_SEASON = 2021
VET_HOLDOUT_TARGET_SEASONS = (2022, 2023, 2024, 2025)

# Artifacts (never overwrite redraft/dynasty filenames)
VET_MODEL_FILE = "hgb_veteran_next_ppr.joblib"
VET_METRICS_FILE = "model_metrics_veteran.json"
VET_FEATURES_CSV = "ml_features_veteran.csv"
VET_PANEL_CSV = "veteran_panel.csv"
VET_BASELINE_CSV = "model_vs_baseline_veteran.csv"
VET_CORR_CSV = "feature_correlation_veteran.csv"
VET_DRAFT_BOARD_CSV = "draft_board_unified.csv"

TARGET = "ppr_next"

# Component stats projected on their own so a week can be built bottom-up.
# Each gets a "<col>_next" label in the panel and its own model per position.
STAT_LABEL_COLS = [
    "passing_yards",
    "passing_tds",
    "interceptions",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "targets",
    "receptions",
    "receiving_yards",
    "receiving_tds",
    "fumbles_lost",
    "games",
]
STAT_TARGETS = [f"{c}_next" for c in STAT_LABEL_COLS]

VET_STAT_MODEL_FILE = "hgb_veteran_stats.joblib"
VET_STAT_METRICS_FILE = "model_metrics_veteran_stats.json"
VET_WEEKLY_CSV = "weekly_projections.csv"
VET_WEEKLY_COMPARE_CSV = "weekly_vs_season_projection.csv"

ID_COLS = ["gsis_id", "player_name", "position", "season", "team"]

# Phase 1 + Phase 2 feature columns
FEATURE_COLS = [
    "ppr",
    "games",
    "ppr_per_game",
    "carries",
    "targets",
    "receptions",
    "rushing_yards",
    "receiving_yards",
    "passing_yards",
    "rushing_tds",
    "receiving_tds",
    "passing_tds",
    "touches",
    "lag1_ppr",
    "lag2_ppr",
    "delta_ppr",
    "delta_touches",
    "ppr_trail3_mean",
    "career_seasons",
    "age",
    "team_changed",
    "off_pass_yards",
    "off_rush_yards",
    "off_pass_rate_proxy",
    "sos_opp_win_pct",
    # Phase 2 — OL / offense EPA / defense context
    "ol_sack_rate",
    "ol_qb_hit_rate",
    "delta_ol_sack_rate",
    "off_epa_per_play",
    "off_pass_epa",
    "off_rush_epa",
    "def_epa_per_play",
    "def_pass_epa",
    "def_rush_epa",
    "opp_def_epa_faced",
    "opp_def_pass_epa_faced",
    "opp_def_rush_epa_faced",
    "next_opp_def_epa_faced",
    "next_opp_def_pass_epa_faced",
    "next_opp_def_rush_epa_faced",
    # Phase 3 — role / NGS
    "off_snap_pct",
    "off_snaps",
    "delta_off_snap_pct",
    "depth_rank",
    "ngs_ryoe",
    "ngs_ryoe_per_att",
    "ngs_rush_efficiency",
    "ngs_avg_separation",
    "ngs_avg_cushion",
    "ngs_yac_oe",
    "ngs_avg_ttt",
    "ngs_cpoe",
    "ngs_aggressiveness",
]

POSITION_FEATURE_COLS: dict[str, list[str]] = {
    "QB": [
        "ppr",
        "games",
        "ppr_per_game",
        "passing_yards",
        "passing_tds",
        "rushing_yards",
        "rushing_tds",
        "lag1_ppr",
        "lag2_ppr",
        "delta_ppr",
        "ppr_trail3_mean",
        "career_seasons",
        "age",
        "team_changed",
        "off_pass_yards",
        "off_pass_rate_proxy",
        "sos_opp_win_pct",
        "ol_sack_rate",
        "ol_qb_hit_rate",
        "delta_ol_sack_rate",
        "off_epa_per_play",
        "off_pass_epa",
        "opp_def_epa_faced",
        "opp_def_pass_epa_faced",
        "next_opp_def_epa_faced",
        "next_opp_def_pass_epa_faced",
        "off_snap_pct",
        "delta_off_snap_pct",
        "depth_rank",
        "ngs_avg_ttt",
        "ngs_cpoe",
        "ngs_aggressiveness",
    ],
    "RB": [
        "ppr",
        "games",
        "ppr_per_game",
        "carries",
        "targets",
        "receptions",
        "rushing_yards",
        "receiving_yards",
        "rushing_tds",
        "receiving_tds",
        "touches",
        "lag1_ppr",
        "lag2_ppr",
        "delta_ppr",
        "delta_touches",
        "ppr_trail3_mean",
        "career_seasons",
        "age",
        "team_changed",
        "off_rush_yards",
        "off_pass_rate_proxy",
        "sos_opp_win_pct",
        "ol_sack_rate",
        "delta_ol_sack_rate",
        "off_epa_per_play",
        "off_rush_epa",
        "opp_def_epa_faced",
        "opp_def_rush_epa_faced",
        "next_opp_def_epa_faced",
        "next_opp_def_rush_epa_faced",
        "off_snap_pct",
        "delta_off_snap_pct",
        "depth_rank",
        "ngs_ryoe",
        "ngs_ryoe_per_att",
        "ngs_rush_efficiency",
    ],
    "WR": [
        "ppr",
        "games",
        "ppr_per_game",
        "targets",
        "receptions",
        "receiving_yards",
        "receiving_tds",
        "touches",
        "lag1_ppr",
        "lag2_ppr",
        "delta_ppr",
        "delta_touches",
        "ppr_trail3_mean",
        "career_seasons",
        "age",
        "team_changed",
        "off_pass_yards",
        "off_pass_rate_proxy",
        "sos_opp_win_pct",
        "ol_sack_rate",
        "delta_ol_sack_rate",
        "off_epa_per_play",
        "off_pass_epa",
        "opp_def_epa_faced",
        "opp_def_pass_epa_faced",
        "next_opp_def_epa_faced",
        "next_opp_def_pass_epa_faced",
        "off_snap_pct",
        "delta_off_snap_pct",
        "depth_rank",
        "ngs_avg_separation",
        "ngs_yac_oe",
    ],
    "TE": [
        "ppr",
        "games",
        "ppr_per_game",
        "targets",
        "receptions",
        "receiving_yards",
        "receiving_tds",
        "touches",
        "lag1_ppr",
        "lag2_ppr",
        "delta_ppr",
        "delta_touches",
        "ppr_trail3_mean",
        "career_seasons",
        "age",
        "team_changed",
        "off_pass_yards",
        "off_pass_rate_proxy",
        "sos_opp_win_pct",
        "ol_sack_rate",
        "delta_ol_sack_rate",
        "off_epa_per_play",
        "off_pass_epa",
        "opp_def_epa_faced",
        "opp_def_pass_epa_faced",
        "next_opp_def_epa_faced",
        "next_opp_def_pass_epa_faced",
        "off_snap_pct",
        "delta_off_snap_pct",
        "depth_rank",
        "ngs_avg_separation",
        "ngs_yac_oe",
    ],
}

__all__ = [
    "CSV_OUTPUT_DIR",
    "FEATURE_COLS",
    "ID_COLS",
    "MODELS_DIR",
    "POSITION_FEATURE_COLS",
    "SKILL_POSITIONS",
    "STAT_LABEL_COLS",
    "STAT_TARGETS",
    "TARGET",
    "VET_STAT_METRICS_FILE",
    "VET_STAT_MODEL_FILE",
    "VET_WEEKLY_COMPARE_CSV",
    "VET_WEEKLY_CSV",
    "VET_BASELINE_CSV",
    "VET_CORR_CSV",
    "VET_DRAFT_BOARD_CSV",
    "VET_FEATURES_CSV",
    "VET_HOLDOUT_TARGET_SEASONS",
    "VET_METRICS_FILE",
    "VET_MODEL_FILE",
    "VET_PANEL_CSV",
    "VET_SEASON_MAX",
    "VET_SEASON_MIN",
    "VET_TUNING_TARGET_SEASON",
]
